//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Choicers = new HashSet<Choicer>();
            this.Questers = new HashSet<Quester>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Choicer> Choicers { get; set; }
        public virtual ICollection<Quester> Questers { get; set; }
    }
}
