//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceTest
    {
        public int ChoiceTestID { get; set; }
        public Nullable<int> FCTestID { get; set; }
        public Nullable<int> FChoicerID { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> TimeSkip { get; set; }
        public Nullable<int> TestAppearance { get; set; }
    
        public virtual Choicer Choicer { get; set; }
        public virtual CTest CTest { get; set; }
    }
}
