//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestTest
    {
        public int QuestTestID { get; set; }
        public Nullable<int> FQTestID { get; set; }
        public Nullable<int> FQuesterID { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> TImeSkip { get; set; }
        public Nullable<int> TestAppearance { get; set; }
    
        public virtual QTest QTest { get; set; }
        public virtual Quester Quester { get; set; }
    }
}
