//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quester
    {
        public Quester()
        {
            this.QuestShares = new HashSet<QuestShare>();
            this.QuestTests = new HashSet<QuestTest>();
        }
    
        public int QuesterID { get; set; }
        public Nullable<int> FCategoryID { get; set; }
        public Nullable<int> FQUserID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Hint { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<bool> IsShareOnline { get; set; }
        public Nullable<bool> IsFavourite { get; set; }
        public Nullable<bool> IsSkip { get; set; }
        public Nullable<int> Appearance { get; set; }
        public Nullable<int> WAppearance { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuestShare> QuestShares { get; set; }
        public virtual ICollection<QuestTest> QuestTests { get; set; }
    }
}
