//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TuitionCloudDBEntities : DbContext
    {
        public TuitionCloudDBEntities()
            : base("name=TuitionCloudDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Choicer> Choicers { get; set; }
        public virtual DbSet<ChoiceShare> ChoiceShares { get; set; }
        public virtual DbSet<ChoiceTest> ChoiceTests { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CTest> CTests { get; set; }
        public virtual DbSet<CTestShare> CTestShares { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<QTest> QTests { get; set; }
        public virtual DbSet<QTestShare> QTestShares { get; set; }
        public virtual DbSet<Quester> Questers { get; set; }
        public virtual DbSet<QuestShare> QuestShares { get; set; }
        public virtual DbSet<QuestTest> QuestTests { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestShare> TestShares { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Website> Websites { get; set; }
        public virtual DbSet<WordShare> WordShares { get; set; }
        public virtual DbSet<WordTest> WordTests { get; set; }
        public virtual DbSet<Wordutopia> Wordutopias { get; set; }
        public virtual DbSet<WTest> WTests { get; set; }
    }
}
