//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestShare
    {
        public int TestShareID { get; set; }
        public Nullable<int> FTestID { get; set; }
        public Nullable<int> ShareBy { get; set; }
        public Nullable<int> ShareTo { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ShareDate { get; set; }
    
        public virtual WTest WTest { get; set; }
    }
}
