//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Categories = new HashSet<Category>();
            this.Choicers = new HashSet<Choicer>();
            this.Contacts = new HashSet<Contact>();
            this.CTests = new HashSet<CTest>();
            this.News = new HashSet<News>();
            this.Notes = new HashSet<Note>();
            this.QTests = new HashSet<QTest>();
            this.Questers = new HashSet<Quester>();
            this.Wordutopias = new HashSet<Wordutopia>();
            this.WTests = new HashSet<WTest>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> FUserWebID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<System.DateTime> SubscribeDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Choicer> Choicers { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<CTest> CTests { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<QTest> QTests { get; set; }
        public virtual ICollection<Quester> Questers { get; set; }
        public virtual Website Website { get; set; }
        public virtual ICollection<Wordutopia> Wordutopias { get; set; }
        public virtual ICollection<WTest> WTests { get; set; }
    }
}
