//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wordutopia
    {
        public Wordutopia()
        {
            this.WordShares = new HashSet<WordShare>();
            this.WordTests = new HashSet<WordTest>();
        }
    
        public int WordID { get; set; }
        public Nullable<int> FWUserID { get; set; }
        public string Word { get; set; }
        public string Pronounciation { get; set; }
        public string Phrase { get; set; }
        public string Hint { get; set; }
        public string Definition { get; set; }
        public string Synonym { get; set; }
        public Nullable<bool> IsShareOnline { get; set; }
        public Nullable<bool> IsFavourite { get; set; }
        public Nullable<bool> IsSkip { get; set; }
        public Nullable<int> Appearance { get; set; }
        public Nullable<int> WAppreance { get; set; }
        public Nullable<int> Score { get; set; }
        public string AdditionInfo { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<WordShare> WordShares { get; set; }
        public virtual ICollection<WordTest> WordTests { get; set; }
    }
}
