//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordTest
    {
        public int WordTestID { get; set; }
        public Nullable<int> FWtestID { get; set; }
        public Nullable<int> FWordID { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> TImeSkip { get; set; }
        public Nullable<int> TestAppearance { get; set; }
    
        public virtual Wordutopia Wordutopia { get; set; }
        public virtual WTest WTest { get; set; }
    }
}
