//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tutioncloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordShare
    {
        public int WShareID { get; set; }
        public Nullable<int> FWordID { get; set; }
        public Nullable<int> UserTo { get; set; }
        public Nullable<int> UserFrom { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ShareDate { get; set; }
    
        public virtual Wordutopia Wordutopia { get; set; }
    }
}
